POST http://api.platform.local/v1/signup
Accept: application/json
Content-Type: application/json

{
  "email": "xjyx105@mail.ru",
  "firstname": "Никита",
  "lastname": "Ярков",
  "password": "123qwe",
  "password_confirm": "123qwe"
}

###
POST http://api.platform.local/v1/login
Accept: application/json
Content-Type: application/json

{
  "identity": "xjyx10@mail.ru",
  "password": "12345678",
  "rememberMe": true
}

###
GET http://api.platform.local/v1/cabinet/get-info
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6Im1zS2RXREtvMjZZWEJTa2YzdmwzSjA0UnViQW55TStTSkpJZXI4Y21ZRDg9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6Im1zS2RXREtvMjZZWEJTa2YzdmwzSjA0UnViQW55TStTSkpJZXI4Y21ZRDg9IiwiaWF0IjoxNjg0OTQ2NDE5LCJleHAiOjE2ODc1Mzg0MTksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgyMDIxMCIsImV4cGlyZXMiOjE2ODc1Mzg0MTl9fQ.2PiZRxF7B-KRJ0rvOa17kVyIyDGRHUAS8z8U0VLNG6k

###
GET http://api.platform.local/v1/cabinet/essay
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSJ9.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSIsImlhdCI6MTY4NTExOTY5MCwiZXhwIjoxNjg3NzExNjkwLCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTAiLCJleHBpcmVzIjoxNjg3NzExNjkwfX0.1ljc5Ri5APID28y-oG5TEi32qNDh6pf5iH4Qm77yHo4

###
GET http://api.platform.local/v1/cabinet/essay?id=3
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSJ9.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSIsImlhdCI6MTY4NTExOTY5MCwiZXhwIjoxNjg3NzExNjkwLCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTAiLCJleHBpcmVzIjoxNjg3NzExNjkwfX0.1ljc5Ri5APID28y-oG5TEi32qNDh6pf5iH4Qm77yHo4

###
POST http://api.platform.local/v1/cabinet/essay
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSJ9.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSIsImlhdCI6MTY4NTExOTY5MCwiZXhwIjoxNjg3NzExNjkwLCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTAiLCJleHBpcmVzIjoxNjg3NzExNjkwfX0.1ljc5Ri5APID28y-oG5TEi32qNDh6pf5iH4Qm77yHo4
Content-Type: application/json

{
  "topic": "Test2",
  "text": "qwerty"
}

###
PUT http://api.platform.local/v1/cabinet/essay
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSJ9.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSIsImlhdCI6MTY4NTExOTY5MCwiZXhwIjoxNjg3NzExNjkwLCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTAiLCJleHBpcmVzIjoxNjg3NzExNjkwfX0.1ljc5Ri5APID28y-oG5TEi32qNDh6pf5iH4Qm77yHo4
Content-Type: application/json

{
  "topic": "Test",
  "text": "test text"
}

###
DELETE http://api.platform.local/v1/cabinet/delete-essay/3
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSJ9.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InRodHpEVk1BQitZR0d3RVBIWjFJd21QU0RJNHc5a0pEZnI0XC8zelBBbGtzPSIsImlhdCI6MTY4NTExOTY5MCwiZXhwIjoxNjg3NzExNjkwLCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTAiLCJleHBpcmVzIjoxNjg3NzExNjkwfX0.1ljc5Ri5APID28y-oG5TEi32qNDh6pf5iH4Qm77yHo4
Content-Type: application/json

###
GET http://api.platform.local/v1/cabinet/countries
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6Im5GYTB3V1E5eGZFTG1JcnA2ZzFEblMxT1RqVzMrQTczQlwvditOXC9lRkUzOD0ifQ.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6Im5GYTB3V1E5eGZFTG1JcnA2ZzFEblMxT1RqVzMrQTczQlwvditOXC9lRkUzOD0iLCJpYXQiOjE2ODUxMTYzNTUsImV4cCI6MTY4NzcwODM1NSwidWlkIjp7InVzZXJuYW1lIjoieGp5eDEwIiwiZXhwaXJlcyI6MTY4NzcwODM1NX19.NSghNOGCb63sKHVQroIyDV-h06aP85JePqX2mEFSJ0s

###
GET http://api.platform.local/v1/cabinet/specializations
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6Im5GYTB3V1E5eGZFTG1JcnA2ZzFEblMxT1RqVzMrQTczQlwvditOXC9lRkUzOD0ifQ.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6Im5GYTB3V1E5eGZFTG1JcnA2ZzFEblMxT1RqVzMrQTczQlwvditOXC9lRkUzOD0iLCJpYXQiOjE2ODUxMTYzNTUsImV4cCI6MTY4NzcwODM1NSwidWlkIjp7InVzZXJuYW1lIjoieGp5eDEwIiwiZXhwaXJlcyI6MTY4NzcwODM1NX19.NSghNOGCb63sKHVQroIyDV-h06aP85JePqX2mEFSJ0s

###
GET http://api.platform.local/v1/cabinet/directions
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImtaSVFJNVwvNSs4XC9yVU9vKzlvMGtLaHFBQlJ5R3pmQTdyS2VMblludW1LUT0ifQ.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6ImtaSVFJNVwvNSs4XC9yVU9vKzlvMGtLaHFBQlJ5R3pmQTdyS2VMblludW1LUT0iLCJpYXQiOjE2ODUxNzk1OTMsImV4cCI6MTY4Nzc3MTU5MywidWlkIjp7InVzZXJuYW1lIjoieGp5eDEwIiwiZXhwaXJlcyI6MTY4Nzc3MTU5M319.jbcJvUY9Qc-ZFvnSZgfVD5thSXQqA6A1dIeItjan5Zg

###
GET http://api.platform.local/v1/cabinet/profile
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9IiwiaWF0IjoxNjg1Mjk1MDY1LCJleHAiOjE2ODc4ODcwNjUsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDEiLCJleHBpcmVzIjoxNjg3ODg3MDY1fX0.y7Wam7GzP2tKhdAIRQB5tQAqXXo2uSUKvlr_Y1rRrEo

###
POST http://api.platform.local/v1/cabinet/update-profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9IiwiaWF0IjoxNjg1Mjk1MDY1LCJleHAiOjE2ODc4ODcwNjUsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDEiLCJleHBpcmVzIjoxNjg3ODg3MDY1fX0.y7Wam7GzP2tKhdAIRQB5tQAqXXo2uSUKvlr_Y1rRrEo


{
  "age": "853324380"
}

###
POST http://api.platform.local/v1/cabinet/change-password
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6Ikd2QnZRczJweDRHOHdvaHQxdUhTU2lqNjNaYWw4dFpoV1hJYkVEU2toRWc9In0.eyJpc3MiOiJodHRwOlwvXC9hcGkucGxhdGZvcm0ubG9jYWwiLCJhdWQiOiJodHRwOlwvXC9hcGkucGxhdGZvcm0ubG9jYWwiLCJqdGkiOiJHdkJ2UXMycHg0Rzh3b2h0MXVIU1NpajYzWmFsOHRaaFdYSWJFRFNraEVnPSIsImlhdCI6MTY4NDY2MDMyMCwiZXhwIjoxNjg3MjUyMzIwLCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTEiLCJleHBpcmVzIjoxNjg3MjUyMzIwfX0.G34c3pnmRsg4dryQyDXFHbZbSKqEfo_KXAzSNEfZjQo

{
  "password": "1234qwer",
  "password_confirm": "1234qwer"
}

###
POST http://api.platform.local/v1/cabinet/create-candidate-order
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjFlbDQzOVREVm93Yk9qK0VqQXdYc0t1aGpIb3A4dnEyTXNhUW5cLzBnaytFPSJ9.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjFlbDQzOVREVm93Yk9qK0VqQXdYc0t1aGpIb3A4dnEyTXNhUW5cLzBnaytFPSIsImlhdCI6MTY4NTI5ODk3MywiZXhwIjoxNjg3ODkwOTczLCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTA1IiwiZXhwaXJlcyI6MTY4Nzg5MDk3M319.fr8F0YwALSZb4RkEh04XxdUbHyyNWgtUIoQzY9ZLxyg

###
GET http://api.platform.local/v1/cabinet/get-candidate
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjVncWRoUnA5XC9MMHU1MXBhYlBcL1RpVng1bTZzY2VDZ3QydFdGMmFOY1hIND0ifQ.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjVncWRoUnA5XC9MMHU1MXBhYlBcL1RpVng1bTZzY2VDZ3QydFdGMmFOY1hIND0iLCJpYXQiOjE2ODUxODY0NTgsImV4cCI6MTY4Nzc3ODQ1OCwidWlkIjp7InVzZXJuYW1lIjoieGp5eDEwIiwiZXhwaXJlcyI6MTY4Nzc3ODQ1OH19.l4qbLODA2IWmV3VNcrqdZOGoA_Gn-HP2sZybZ9baZzs

###
POST http://api.platform.local/v1/cabinet/update-direction/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImtaSVFJNVwvNSs4XC9yVU9vKzlvMGtLaHFBQlJ5R3pmQTdyS2VMblludW1LUT0ifQ.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6ImtaSVFJNVwvNSs4XC9yVU9vKzlvMGtLaHFBQlJ5R3pmQTdyS2VMblludW1LUT0iLCJpYXQiOjE2ODUxNzk1OTMsImV4cCI6MTY4Nzc3MTU5MywidWlkIjp7InVzZXJuYW1lIjoieGp5eDEwIiwiZXhwaXJlcyI6MTY4Nzc3MTU5M319.jbcJvUY9Qc-ZFvnSZgfVD5thSXQqA6A1dIeItjan5Zg

{
  "direction": 2
}

###
POST http://api-devplus.ru.xsph.ru/public/web/api/v1/cabinet/add-education
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IlNtRERGdEtUeEpJZ3dYQTJvaStsUkp6anpFb2E5NXM4OVl4cm1BeHpJT3c9In0.eyJpc3MiOiJodHRwOlwvXC9hcGktZGV2cGx1cy5ydS54c3BoLnJ1XC9hcGkiLCJhdWQiOiJodHRwOlwvXC9hcGktZGV2cGx1cy5ydS54c3BoLnJ1XC9hcGkiLCJqdGkiOiJTbURERnRLVHhKSWd3WEEyb2krbFJKemp6RW9hOTVzODlZeHJtQXh6SU93PSIsImlhdCI6MTY4NTIxODczOCwiZXhwIjoxNjg3ODEwNzM4LCJ1aWQiOnsidXNlcm5hbWUiOiJ4anl4MTAiLCJleHBpcmVzIjoxNjg3ODEwNzM4fX0.cvoC6QeE0vzFDfrT2P_NA_s9S1rW4-ijElNpp7ZNX-Y

{
  "level": 1,
  "name": "as",
  "address": "rge",
  "city": "43gv",
  "speciality": "af",
  "date_start": 2020,
  "date_end": 2025
}

###
POST http://api.platform.local/v1/cabinet/add-experience
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InBRZGgxT0s5b2cwUGc4bHloaG5wOXNTNDRoQXNzMVlBWndTZndEQUY1MUk9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InBRZGgxT0s5b2cwUGc4bHloaG5wOXNTNDRoQXNzMVlBWndTZndEQUY1MUk9IiwiaWF0IjoxNjg1MjAzMjAzLCJleHAiOjE2ODc3OTUyMDMsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMCIsImV4cGlyZXMiOjE2ODc3OTUyMDN9fQ.euBOnSmnWr6dl1BkECWAnjSyOrt8xdoOH-l2yDsVNbE

{
  "income": 100000,
  "name": "Россельхоз",
  "address": "г. Киров, ул. Володарского 154",
  "post": "Курьер",
  "responsibilities": "Доставка еды",
  "date_start": 2020,
  "date_end": 2025,
  "key_skills": [
    1,
    2,
    3,
    4,
    9
  ]
}

###
POST http://api.platform.local/v1/cabinet/next-stage
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InBRZGgxT0s5b2cwUGc4bHloaG5wOXNTNDRoQXNzMVlBWndTZndEQUY1MUk9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InBRZGgxT0s5b2cwUGc4bHloaG5wOXNTNDRoQXNzMVlBWndTZndEQUY1MUk9IiwiaWF0IjoxNjg1MjAzMjAzLCJleHAiOjE2ODc3OTUyMDMsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMCIsImV4cGlyZXMiOjE2ODc3OTUyMDN9fQ.euBOnSmnWr6dl1BkECWAnjSyOrt8xdoOH-l2yDsVNbE


###
GET http://api.platform.local/v1/cabinet/list-candidate
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6InBRZGgxT0s5b2cwUGc4bHloaG5wOXNTNDRoQXNzMVlBWndTZndEQUY1MUk9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6InBRZGgxT0s5b2cwUGc4bHloaG5wOXNTNDRoQXNzMVlBWndTZndEQUY1MUk9IiwiaWF0IjoxNjg1MjAzMjAzLCJleHAiOjE2ODc3OTUyMDMsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMCIsImV4cGlyZXMiOjE2ODc3OTUyMDN9fQ.euBOnSmnWr6dl1BkECWAnjSyOrt8xdoOH-l2yDsVNbE

###
POST http://api.platform.local/v1/cabinet/create-vacancy
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9IiwiaWF0IjoxNjg1Mjk1MDY1LCJleHAiOjE2ODc4ODcwNjUsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDEiLCJleHBpcmVzIjoxNjg3ODg3MDY1fX0.y7Wam7GzP2tKhdAIRQB5tQAqXXo2uSUKvlr_Y1rRrEo

{
  "income": 100000,
  "geo_lat": 123.2342,
  "geo_lon": 1646584,
  "title": "test",
  "mentor_id": 5
}

###
GET http://api.platform.local/v1/cabinet/get-vacancy/2
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9IiwiaWF0IjoxNjg2MDk1MjM5LCJleHAiOjE2ODg2ODcyMzksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDkiLCJleHBpcmVzIjoxNjg4Njg3MjM5fX0.8m1DBVvrEC4RKKdGQCtadJNJ0xIFojKkKOvXL--tgXY

###
POST http://api.platform.local/v1/cabinet/update-vacancy/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImpUeEhpWHJFZUdCTUYrOTludDZPbXFIV1J3V3M2YUNhS3VtSWt4RGgzUHc9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6ImpUeEhpWHJFZUdCTUYrOTludDZPbXFIV1J3V3M2YUNhS3VtSWt4RGgzUHc9IiwiaWF0IjoxNjg1MjgyODkwLCJleHAiOjE2ODc4NzQ4OTAsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMCIsImV4cGlyZXMiOjE2ODc4NzQ4OTB9fQ.FK2jvNERLILi9OwtsDXhiNkQpra1178_lXhFt3_oBS0

{
  "address": "Kirov",
  "income": 150000
}

###
GET http://api.platform.local/v1/cabinet/list-vacancy?page=1&count=2&direction_id=2
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9IiwiaWF0IjoxNjg2MDk1MjM5LCJleHAiOjE2ODg2ODcyMzksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDkiLCJleHBpcmVzIjoxNjg4Njg3MjM5fX0.8m1DBVvrEC4RKKdGQCtadJNJ0xIFojKkKOvXL--tgXY

###
GET http://api.platform.local/v1/cabinet/organization/list-vacancy
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9IiwiaWF0IjoxNjg2MDk1MjM5LCJleHAiOjE2ODg2ODcyMzksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDkiLCJleHBpcmVzIjoxNjg4Njg3MjM5fX0.8m1DBVvrEC4RKKdGQCtadJNJ0xIFojKkKOvXL--tgXY

###
GET http://api.platform.local/v1/cabinet/list-mentors
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9IiwiaWF0IjoxNjg2MDk1MjM5LCJleHAiOjE2ODg2ODcyMzksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDkiLCJleHBpcmVzIjoxNjg4Njg3MjM5fX0.8m1DBVvrEC4RKKdGQCtadJNJ0xIFojKkKOvXL--tgXY

###
GET http://api.platform.local/v1/cabinet/list-candidate
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6ImpCNTVlYm5Dd25SYnUwQjduRjBvd1AwU2lGaUI4ejVqU00relBpc3RJaVk9IiwiaWF0IjoxNjg1Mjk1MDY1LCJleHAiOjE2ODc4ODcwNjUsInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDEiLCJleHBpcmVzIjoxNjg3ODg3MDY1fX0.y7Wam7GzP2tKhdAIRQB5tQAqXXo2uSUKvlr_Y1rRrEo

###
POST http://api.platform.local/v1/cabinet/reply
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9IiwiaWF0IjoxNjg2MDk1MjM5LCJleHAiOjE2ODg2ODcyMzksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDkiLCJleHBpcmVzIjoxNjg4Njg3MjM5fX0.8m1DBVvrEC4RKKdGQCtadJNJ0xIFojKkKOvXL--tgXY

{
  "vacancy_id": 4
}

###
GET http://api.platform.local/v1/cabinet/get-mentor
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9IiwiaWF0IjoxNjg2MDk1MjM5LCJleHAiOjE2ODg2ODcyMzksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDkiLCJleHBpcmVzIjoxNjg4Njg3MjM5fX0.8m1DBVvrEC4RKKdGQCtadJNJ0xIFojKkKOvXL--tgXY

###
GET http://api.platform.local/v1/cabinet/list-replies
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9In0.eyJpc3MiOiJodHRwOlwvXC9wbGF0Zm9ybS5sb2NhbFwvYXBpIiwiYXVkIjoiaHR0cDpcL1wvcGxhdGZvcm0ubG9jYWxcL2FwaSIsImp0aSI6IjM5cFRmcHduNWEyVmJHSSs2aDRUTEVITU0wYXYyZUdsWHNacllOVEZCNlE9IiwiaWF0IjoxNjg2MDk1MjM5LCJleHAiOjE2ODg2ODcyMzksInVpZCI6eyJ1c2VybmFtZSI6InhqeXgxMDkiLCJleHBpcmVzIjoxNjg4Njg3MjM5fX0.8m1DBVvrEC4RKKdGQCtadJNJ0xIFojKkKOvXL--tgXY
